@startuml "General Architecture"

title "General Architecture"

frame "Data Sources" as ds {
    database db
    database cloud as s3
    database local

    [Categories]
    [Messages]

    db -down-> Messages
    db -down-> Categories

    s3 -down-> Messages
    s3 -down-> Categories

    local -down-> Messages
    local -down-> Categories
}

frame "Orchestration" as orc {
    [Logger]
    [Tracer]
    component Processor as Processor {
        port " " as cin
        port " " as min
    }
}

Messages --> cin
Categories --> min

frame "Parallel Processing" as pro {
    [Message Processor] as mp
    [Category Processor] as cp

    component "Regular Expression" as regex
    component "Cosine Similarity" as cosine
    component "LLM Categorization" as llm

    cp -down-> regex
    cp -down-> cosine
    cp -down-> llm

    regex ..right..> llm
    llm ..right..> cosine
}

frame "Categorized Message Destinations" as dd {
    component Destination as dest {
        portout " " as pdbd
        portout " " as ps3d
        portout " " as plocald
    }
    database " db  " as dbd
    database "cloud" as s3d
    database "local" as locald

    pdbd -down-> dbd
    ps3d -down-> s3d
    plocald -down-> locald
}

frame "Analysis and Visualization" {
    database "Data Warehouse" as dw {
        port " " as pdwds
        port " " as pdworc
        port " " as pdwpro
        port " " as pdwpdd
        portout " " as dwo
    }

    component Grafana as grafana {
        port " " as grafanadw

        component "Infrastructure View"
        component "Tracing View"
        component "Data View"
        component "Reports View"
    }

    dwo -down-> grafanadw
}

dest <-right- cp
[Processor] -> mp
mp --> cp

' ds -down-> pdwds
' orc -down-> pdworc
' pro -down-> pdwpro
' dd -down-> pdwpdd

@enduml