@startuml "General Architecture"

start

repeat :load message;
    :load categories;
    :spawn message categorization;
    :group categories;
    :spawn category group message categorization;
    if (category is applicable?) then (yes) :send category to destination;
repeat while (more messages?) is (yes)
-> no;

stop

@enduml