create table categories (
    id int generated by default as identity primary key, 
    category varchar(250), 
    run_group int, 
    regex text, 
    parent int, 
    llmcheck boolean not null default false, 
    description text, 
    constraint fk_categories_parent_id foreign key (parent) references categories(id)
);

create table messages (
    id int generated by default as identity primary key,
    content text
);