from collections import namedtuple as nt
import datetime as dt
import psycopg2 as g2
import random as rand
import json

Message=nt('Message',['text','lat','lon'])
TimeMessage=nt('Message',['id','ts','text','lat','long'])

def random_date(start,finish):
    delta=finish-start
    seconds=rand.randrange(int(delta.total_seconds()))

    return start + dt.timedelta(seconds=seconds)

try:
    with g2.connect('postgresql://postgres:postgres@localhost:5432/messages') as conn:
        with conn.cursor() as cur:
            cur.execute('create schema sample;')
except g2.errors.DuplicateSchema:
    pass

try:
    with g2.connect('postgresql://postgres:postgres@localhost:5432/messages') as conn:
        with conn.cursor() as cur:
            cur.execute("""
                    create table sample.messages (
                        id int not null generated by default as identity,
                        sent timestamptz not null default now(),
                        content text not null,
                        latitude numeric,
                        longitude numeric,
                        constraint pk_sample_messages primary key (id)
                    )
                    """)
except g2.errors.DuplicateTable:
    pass

try:
    with g2.connect('postgresql://postgres:postgres@localhost:5432/messages') as conn:
        with conn.cursor() as cur:
            cur.execute("""
                    create index idx_sample_messages_sent_date on sample.messages ((timezone('UTC', sent)::DATE));
                    """)
except g2.errors.DuplicateTable:
    pass

try:
    with g2.connect('postgresql://postgres:postgres@localhost:5432/messages') as conn:
        with conn.cursor() as cur:
            cur.execute("""
                    create table sample.messages (
                        id int not null generated by default as identity,
                        sent timestamptz not null default now(),
                        content text not null,
                        latitude numeric,
                        longitude numeric,
                        constraint pk_sample_messages primary key (id)
                    )
                    """)
except g2.errors.DuplicateTable:
    pass

with open("./data/c_0.json","r") as fs, g2.connect('postgresql://postgres:postgres@localhost:5432/messages') as conn:
    with conn.cursor() as cur:
        count=0
        for line in fs.readlines():
            count+=1
            raw=json.loads(line)
            record=Message(raw['text'],raw['coordinates'][0],raw['coordinates'][1])
            trecord=TimeMessage(count,random_date(dt.datetime(2026,1,1,12,0,0),dt.datetime(2026,4,26,12,0,0)),record.text,float(record.lat),float(record.lon))

            print(trecord)
            cur.execute("""
                        insert into sample.messages (id,sent,content,latitude,longitude)
                        values (%s,%s,%s,%s,%s)
                        on conflict (id) do nothing
                        """,trecord)